spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/zm?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver 
    type: com.zaxxer.hikari.HikariDataSource
    
    
    hikari: 
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上  
      maximumPoolSize: 100 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)  
#    zipkin: 
#      base-url: http://localhost:9061/ # use zipkin configuration
#    sleuth: 
#      sampler: 
#        percentage: 0.1 #zipkin采样率，默认为0.1，改为1后全采样，但是会降低接口调用效率
      
mybatis: 
   mapperLocations: classpath*:trade/mapper/*.xml 
   typeAliasesPackage: trade.model 
